# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Data Monster'
tagline:          'No tagline yet'
description:      'Data explorations by a data scientist hobbyist.'
# <a href="http://hyde.getpoole.com">Hyde</a> theme produced by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              'https://sachbhat.github.io'
baseurl:          '/'

author:
  name:           'Sachin Bhatia'
  url:            https://twitter.com/sachbhat

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sachbhat/

future: true
