# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Inversion
tagline:             'Learning by writing.'
description:         'Deep data dives into subjects important to me (education, equity, social justice), notes on books read, and other miscellaneous things.'
url:                 https://sachbhat.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sachin Bhatia
  url:               https://twitter.com/sachbhat
  email:             sachinb#blog@gmail.com

# Custom vars
version:             1.0.0

excerpt_separator: <!--more-->
